library(magrittr)
library(here)
setwd(here())

download.file('https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.1.0-SNAPSHOT/openapi-generator-cli-6.1.0-20220906.004906-108.jar',
              destfile = 'inst/script/openapi-generator.jar')
download.file('https://dev.gemma.msl.ubc.ca/rest/v2/openapi.json','inst/script/openapi.json')
api_file = jsonlite::fromJSON(readLines('inst/script/openapi.json'))

system('java -jar inst/script/openapi-generator.jar generate -i inst/script/openapi.json -g r --skip-validate-spec --additional-properties=operationIdNaming=snake_case,packageName=gemma.R -o inst/script/auto_gen_code')

auto_gen_files = readLines('inst/script/auto_gen_code/.openapi-generator/FILES')

R_files = auto_gen_files[grepl('^R/',auto_gen_files)]
monolith = 'R/openapi_generated.R'
# some cleanups on autogenerated documentation so the tests pass

for (f in R_files){
    file = readLines(glue::glue('inst/script/auto_gen_code/{f}'))

    file[grepl('@export',file)] %<>% gsub("#' @export","#' @keywords internal",.)
    file[grepl("#'",file)] = gsub('\\[|\\]','',file[grepl("#'",file)])

    cat(file,sep = '\n',file = monolith,append = TRUE)
    cat('\n',file=monolith,append = TRUE)
}

# fixed after https://github.com/OpenAPITools/openapi-generator/issues/13328
# # remove forced authentication
# default = readLines('R/default_api.R')
# auth_code = grepl("# HTTP basic auth",default)
# for (i in which(auth_code)){
#     default[i+1] = default[i+1]  %>%
#         gsub('is.null','!is.null',.)
#     default[i+2] = paste0("  ",default[i+4])
#     default[i+4] = ""
# }


method_names =
    api_file$paths %>%
    purrr::map('get') %>%
    purrr::map_chr('operationId') %>%
    snakecase::to_snake_case()
devtools::load_all()

api = DefaultApi$new()
api$api_client$base_path = gsub('/$','',gemmaPath())

expose_fname = 'R/zz_open_api_expose.R'

method_names %>% lapply(function(x){
    f = function(){}
    formals(f) = formals(api[[x]])
    body(f) = quote({
        api = DefaultApi$new()
        api$api_client$base_path = gsub('/$','',gemmaPath())

        if (!is.null(getOption('gemma.username')) && !is.null(getOption('gemma.password'))){
            api_instance$api_client$username <- getOption('gemma.username')
            api_instance$api_client$password <- getOption('gemma.password')
        }
        call <- match.call()
        call[[1]] <- api[[fname]]
        eval(call)

    })
    body(f) <- body(f) %>% as.list() %>%
        append(str2expression(glue::glue('fname = "{x}"')),1) %>% as.call()
    f

}) -> gemma_api
names(gemma_api) = method_names

cat("#' Full API wrapper
#'
#' Exposes the full Gemma API. Auto generated using
#' \\href{https://openapi-generator.tech/}{OpenAPI generator}
#' Exposed to user to allow access unsupported endpoints
#' by the main package.
#' @seealso \\code{\\link{gemmaCall}}
#' @inheritSection DefaultApi Methods
#'
#' @export
#' @keywords misc\n",
    file = expose_fname)
cat('gemma_api = list(\n',file = expose_fname,append = TRUE)

for(x in names(gemma_api)){
    cat(glue::glue('    {x} = {paste(deparse(gemma_api[[x]]),collapse = "\n")}'),file = expose_fname,append = TRUE)
    if (x == names(gemma_api)[length(gemma_api)]){
        cat("\n",file = expose_fname, append = TRUE)
    } else{
        cat(',\n',file = expose_fname, append = TRUE)
    }
}
cat(')',file = expose_fname,append = TRUE)

styler::style_file(expose_fname,transformers = biocthis::bioc_style())
devtools::document()
